name: Compute COGs
on:
  #schedule:
  #  - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    paths: ['*fire.py', '.github/workflows/compute.yml']
jobs:
  compute:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/boettiger-lab/solara-geospatial:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: compute
        run: python fire.py
      - name: push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/datasets/cboettig/solara-data ~/solara-data
          cp *.tif ~/solara-data
          cd ~/solara-data
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.tif
          git commit -a -m "update data" || echo "nothing to commit"
          git push https://cboettig:$HF_TOKEN@huggingface.co/spaces/cboettig/solara-test main

