name: Compute COGs
on:
  #schedule:
  #  - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    paths: ['*fire.py', '.github/workflows/compute.yml']
jobs:
  compute:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/boettiger-lab/solara-geospatial:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: compute
        run: python fire.py
