name: Compute COGs
on:
  #schedule:
  #  - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest
    #container: rocker/geospatial:latest
    container: ghcr.io/boettiger-lab/solara-geospatial:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
           set-safe-directory: '*'
      - name: compute
        run: python fire.py
