name: Docker Image CI
on:
  workflow_dispatch: null
  push:
    paths: ['Dockerfile', 'requirements.txt', '.github/workflows/docker.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'boettiger-lab/solara-test'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'boettiger-lab/solara-test'
        run: docker build . --tag ghcr.io/boettiger-lab/solara-geospatial:latest
      - name: Publish
        if: github.repository == 'boettiger-lab/solara-test'
        run: docker push ghcr.io/boettiger-lab/solara-geospatial:latest
